name: "Tests"

on: [push, pull_request]

jobs:
  run-tests:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    env:
      extensions: mbstring, intl, json, redis, swoole, xdebug, phalcon4
      DATA_API_MYSQL_HOST: 127.0.0.1
      DATA_API_MYSQL_USER: root
      DATA_API_MYSQL_PASS: password
      DATA_API_MYSQL_NAME: baka
      DATA_API_MEMCACHED_HOST: 127.0.0.1
      DATA_API_MEMCACHED_PORT: 11211
      DATA_API_MEMCACHED_WEIGHT: 100
      STRIPE_PUBLIC: ${{ secrets.STRIPE_PUBLIC }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      APP_IP: api.baka.ld
      APP_ENV: development
      PHINX_CONFIG_DIR: storage
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: baka
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          tools: pecl

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-suggest

      - name: Update Composer dependencies
        run: composer update --prefer-dist --no-suggest

      - name: Setup Env Variable
        run: cp storage/ci/.env.example .env

      - name: Setup Phinx
        run: cp storage/ci/phinx.php.example phinx.php
        
      - name: Phinx Migrate Kanvas
        run: vendor/bin/phinx migrate -e development
        
      - name: Phinx Migrate Kanvas Seed
        run: vendor/bin/phinx seed:run

      - name: Run Integration
        if: success()
        run: vendor/bin/codecept run integration

      - name: Run Unit
        if: success()
        run: vendor/bin/codecept run unit

      - name: Run Api
        if: success()
        run: vendor/bin/codecept run api
